<script lang="ts">
  import Plot from '../components/Plot.svelte'
  import { Index } from '../lib/data'
  import { href } from '../lib/router.svelte'
  import { pick } from '../lib/selection.svelte'
  import { loadDataset, loadMeta } from '../lib/store'
  import type { Meta } from '../lib/types'
  import { axis, baseLayout, chrome, identityColor, type Layout, scheme } from '../lib/theme.svelte'

  let idx = $state<Index | null>(null)
  let meta = $state<Meta | null>(null)
  let error = $state('')
  Promise.all([loadDataset(), loadMeta()])
    .then(([ds, m]) => {
      idx = new Index(ds)
      meta = m
    })
    .catch((e) => (error = e.message))

  // Ideas a run generated but the view lacks must be exactly those held back for rating.
  const heldBack = $derived(meta?.sessions.reduce((n, s) => n + (s.revealed ? 0 : s.held_back), 0) ?? 0)

  const runs = $derived(idx?.ds.runs ?? [])
  // The facet runs are grouped by: the first one the runs carry, in its declared order.
  const groupField = $derived.by(() => {
    if (!idx) return undefined
    const used = new Set(runs.flatMap((r) => Object.keys(r.facets ?? {})))
    return idx.ds.fields.find((f) => f.kind === 'facet' && !f.per_scorer && used.has(f.id))
  })

  /** Each run with the ideas it has in the data, so the counts can be checked. */
  const rows = $derived.by(() => {
    if (!idx) return []
    const inData = new Map<string, string[]>()
    for (const i of idx.ds.ideas) if (i.run) inData.set(i.run, [...(inData.get(i.run) ?? []), i.id])
    const order = (r: (typeof runs)[number]) => {
      const v = groupField ? r.facets?.[groupField.id] : undefined
      return groupField?.values?.findIndex((x) => x.id === v) ?? 0
    }
    return [...runs]
      .sort((a, b) => order(a) - order(b) || a.label.localeCompare(b.label))
      .map((r) => ({
        run: r,
        group: groupField ? idx!.valueLabel(groupField.id, r.facets?.[groupField.id] ?? null) : '',
        ids: inData.get(r.id) ?? [],
        generated: r.counts?.generated ?? 0,
      }))
  })

  const totals = $derived.by(() => {
    const byGroup = new Map<string, { runs: number; refused: number; generated: number; inData: number }>()
    for (const r of rows) {
      const t = byGroup.get(r.group) ?? { runs: 0, refused: 0, generated: 0, inData: 0 }
      t.runs++
      if (r.run.status !== 'done') t.refused++
      t.generated += r.generated
      t.inData += r.ids.length
      byGroup.set(r.group, t)
    }
    return [...byGroup.entries()]
  })

  // The runs' figure: one dot per run, ideas generated, by group and by who wrote them.
  const chart = $derived.by(() => {
    void scheme.dark
    if (!idx || !rows.length) return null
    const c = chrome()
    const groups = [...new Set(rows.map((r) => r.group))]
    const authors = [...new Set(rows.map((r) => r.run.author ?? ''))]
    const traces: Layout[] = authors.map((a) => {
      const mine = rows.filter((r) => (r.run.author ?? '') === a)
      return {
        type: 'scatter',
        mode: 'markers',
        name: idx!.generatorLabel(a),
        x: mine.map((r) => r.generated),
        y: mine.map((r) => r.group),
        customdata: mine.map((r) => r.run.id),
        text: mine.map(
          (r) => `<b>${r.run.label}</b><br>${r.generated} ideas` + (r.run.status !== 'done' ? ` · ${r.run.status}` : ''),
        ),
        hovertemplate: '%{text}<extra></extra>',
        marker: {
          color: identityColor(a, idx!.entities),
          size: 11,
          symbol: mine.map((r) => (r.run.status === 'done' ? 'circle' : 'x-open')),
          line: { color: c.surface, width: 2 },
        },
      }
    })
    return {
      traces,
      layout: baseLayout({
        xaxis: axis({ title: { text: 'Ideas generated by the run' }, rangemode: 'tozero' }),
        yaxis: axis({ autorange: 'reversed', showgrid: false, categoryorder: 'array', categoryarray: groups }),
        margin: { l: 16, r: 16, t: 40, b: 52 },
      }),
      height: 90 + 46 * groups.length,
    }
  })

  function showInExplore(r: (typeof rows)[number]) {
    pick(r.run.label, r.ids)
    location.hash = href('/explore')
  }
</script>

{#if error}
  <p class="error">Could not load the data: {error}</p>
{:else if !idx}
  <p class="muted">Loading…</p>
{:else if !runs.length}
  <p class="muted">This dataset records no runs.</p>
{:else}
  <h1>Runs</h1>
  <p class="muted">
    Where the ideas came from. Each dot is one run; a cross is a run that produced nothing (refused
    or failed). Hover for the run, and use the table to show a run's ideas in Explore.
  </p>
  {#if chart}
    <Plot data={chart.traces} layout={chart.layout} filename="runs" height={chart.height} />
  {/if}

  {@const gap = totals.reduce((n, [, t]) => n + t.generated - t.inData, 0)}
  {@const reconciled = gap === heldBack}
  <h2>By {groupField?.label.toLowerCase() ?? 'group'}</h2>
  <p class="check" class:bad={!reconciled}>
    {#if reconciled}
      ✓ Runs generated {totals.reduce((n, [, t]) => n + t.generated, 0).toLocaleString()} ideas: every one is in view{#if heldBack}, except the {heldBack} held back for blind rating{/if}.
    {:else}
      ⚠ Runs generated {gap} more ideas than are in view, but only {heldBack} are held back for rating. Something is missing.
    {/if}
  </p>
  <table class="data">
    <thead>
      <tr>
        <th>{groupField?.label ?? 'Group'}</th>
        <th class="num">Runs</th>
        <th class="num">Refused or failed</th>
        <th class="num">Ideas generated</th>
        <th class="num">Ideas in view</th>
        <th class="num">Held back</th>
      </tr>
    </thead>
    <tbody>
      {#each totals as [g, t] (g)}
        <tr>
          <td>{g}</td>
          <td class="num">{t.runs}</td>
          <td class="num">{t.refused}</td>
          <td class="num">{t.generated}</td>
          <td class="num">{t.inData}</td>
          <td>{t.generated === t.inData ? '' : `${t.generated - t.inData}`}</td>
        </tr>
      {/each}
    </tbody>
  </table>

  <h2>Every run</h2>
  <table class="data">
    <thead>
      <tr>
        <th>Run</th>
        <th>Written by</th>
        <th>Status</th>
        <th class="num">Rounds</th>
        <th class="num">Generated</th>
        <th class="num">In view</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {#each rows as r (r.run.id)}
        <tr>
          <td title={r.run.note}>{r.run.label}</td>
          <td>{idx.generatorLabel(r.run.author ?? '')}</td>
          <td>{r.run.status}</td>
          <td class="num">{r.run.counts?.rounds ?? ''}</td>
          <td class="num">{r.generated}</td>
          <td class="num">{r.ids.length}</td>
          <td>{#if r.ids.length}<button class="btn" onclick={() => showInExplore(r)}>Show in Explore</button>{/if}</td>
        </tr>
      {/each}
    </tbody>
  </table>
{/if}

<style>
  h1 {
    font-size: 1.3rem;
  }

  h2 {
    font-size: 1rem;
    margin: 18px 0 4px;
  }

  .muted {
    color: var(--muted);
    max-width: 90ch;
  }

  .check {
    margin: 4px 0 8px;
  }

  .check.bad {
    color: var(--danger);
    font-weight: 600;
  }

  .error {
    color: var(--danger);
  }
</style>
